name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Check
      run: cargo check --verbose
    - name: Format
      run: cargo fmt --check
    - name: Lint
      run: cargo clippy -- -D clippy::all -W clippy::pedantic
    - name: Test
      run: cargo test --verbose --no-fail-fast
    - name: Build
      run: cargo build

